function createDefaultChoices(now) {
  const timestamp = now || Date.now()

  return [
    {
      id: 'choice_canteen',
      name: '食堂',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice_takeout',
      name: '点外卖',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice_downstairs',
      name: '楼下餐馆',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice_noodle_shop',
      name: '面馆',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice_fast_food',
      name: '快餐',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'choice_simple_meal',
      name: '随便简餐吃点',
      enabled: true,
      category: '',
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ]
}

function createDefaultRecipes(now) {
  const timestamp = now || Date.now()

  return [
    {
      id: 'recipe_tomato_egg',
      name: '西红柿炒鸡蛋',
      category: '家常菜',
      ingredients: ['西红柿 2个', '鸡蛋 3个', '盐 适量', '葱花 少许'],
      steps: ['西红柿切块，鸡蛋打散', '先炒鸡蛋盛出', '炒软西红柿后加入鸡蛋', '调味后出锅'],
      durationMinutes: 15,
      difficulty: '简单',
      note: '配米饭很好吃',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'recipe_egg_fried_rice',
      name: '蛋炒饭',
      category: '快手饭',
      ingredients: ['米饭 1碗', '鸡蛋 2个', '火腿丁 适量', '葱花 少许', '盐 适量'],
      steps: ['鸡蛋打散炒散', '加入米饭翻炒均匀', '放入火腿丁和葱花', '最后调味出锅'],
      durationMinutes: 12,
      difficulty: '简单',
      note: '适合冰箱里剩饭处理',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'recipe_green_pepper_pork',
      name: '青椒炒肉',
      category: '下饭菜',
      ingredients: ['青椒 3个', '瘦肉 200g', '生抽 1勺', '料酒 1勺', '盐 适量'],
      steps: ['瘦肉切片腌制', '青椒切块备用', '先炒肉片，再加入青椒', '调味后快速出锅'],
      durationMinutes: 18,
      difficulty: '普通',
      note: '下饭程度高',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'recipe_coke_chicken_wings',
      name: '可乐鸡翅',
      category: '硬菜',
      ingredients: ['鸡翅 8个', '可乐 1罐', '生抽 2勺', '姜片 3片', '盐 适量'],
      steps: ['鸡翅焯水后划刀', '煎至表面微黄', '倒入可乐和调味料', '收汁后装盘'],
      durationMinutes: 30,
      difficulty: '普通',
      note: '甜咸口，适合解馋',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'recipe_sour_spicy_potato',
      name: '酸辣土豆丝',
      category: '素菜',
      ingredients: ['土豆 2个', '干辣椒 2个', '白醋 1勺', '盐 适量', '蒜末 少许'],
      steps: ['土豆切丝并冲洗淀粉', '热锅爆香蒜末和辣椒', '下土豆丝快速翻炒', '加醋和盐调味出锅'],
      durationMinutes: 10,
      difficulty: '简单',
      note: '快手又开胃',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'recipe_pan_fried_chicken_breast',
      name: '煎鸡胸肉',
      category: '轻食',
      ingredients: ['鸡胸肉 1块', '黑胡椒 适量', '盐 适量', '橄榄油 少许'],
      steps: ['鸡胸肉拍松并腌制', '平底锅少油煎至两面金黄', '静置后切片', '搭配蔬菜即可'],
      durationMinutes: 20,
      difficulty: '简单',
      note: '适合想吃轻一点的时候',
      enabled: true,
      weight: 1,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ]
}

module.exports = {
  createDefaultChoices,
  createDefaultRecipes,
}
